name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Validate MCP Server
      run: npm run test:inspector
      
    - name: Validate Package Contents
      run: |
        npm pack --dry-run 2>&1 | tee pack-output.txt
        echo "Checking that docs are included in package..."
        if grep -q "\.md" pack-output.txt; then
          echo "✅ Docs are included in package"
          grep "\.md" pack-output.txt | wc -l | xargs echo "Found docs files:"
        else
          echo "❌ Docs are missing from package"
          exit 1
        fi
      
    # Uncomment when you add tests
    # - name: Test
    #   run: npm test